import React, { useState, useEffect } from 'react';
import './AIResponse.css';

const AIResponse = ({ 
  content, 
  type = 'default', 
  isVisible = true,
  onComplete = null,
  showIcon = true,
  icon = '🪶'
}) => {
  const [displayedContent, setDisplayedContent] = useState('');
  const [isTyping, setIsTyping] = useState(false);

  useEffect(() => {
    if (content && isVisible) {
      setIsTyping(true);
      setDisplayedContent('');
      
      let currentIndex = 0;
      const typingInterval = setInterval(() => {
        if (currentIndex < content.length) {
          setDisplayedContent(content.slice(0, currentIndex + 1));
          currentIndex++;
        } else {
          setIsTyping(false);
          clearInterval(typingInterval);
          if (onComplete) onComplete();
        }
      }, 20); // Adjust typing speed

      return () => clearInterval(typingInterval);
    }
  }, [content, isVisible, onComplete]);

  if (!isVisible || !content) return null;

  return (
    <div className={`ai-response ai-response--${type} ${isTyping ? 'ai-response--typing' : ''}`}>
      {showIcon && (
        <div className="ai-response__icon">
          {icon}
        </div>
      )}
      <div className="ai-response__content">
        <div className="ai-response__text">
          {displayedContent}
          {isTyping && <span className="ai-response__cursor">|</span>}
        </div>
        {!isTyping && (
          <div className="ai-response__footer">
            <span className="ai-response__timestamp">
              Generated by AI Heritage Guide
            </span>
          </div>
        )}
      </div>
    </div>
  );
};

export default AIResponse;
